Repository dynasty-lang/dynasty-lang, pull requests merged in 2021-02, with the labels that each got.

#15 Fix #14
  antlr/DynastyLang.g4
  antlr/DynastyLexerRuleSet.g4
  src/ast/astNode.ts
  src/visitors/buildAstVisitor.ts
Labels: critical issue, grammar, language feature

#16 Webpackを使ってビルドできるようにする
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#23 オブジェクト/配列のリテラルを追加
  antlr/DynastyLang.g4
  src/ast/astNode.ts
  src/visitors/buildAstVisitor.ts
Labels: grammar, language feature
